name: 🧪 Run Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        config: [Release, Debug]
        vtk-system: [true, false]
        os: [ubuntu-latest, windows-latest, macos-latest]

        exclude:
          - os: macos-latest
            vtk-system: true

          - os: windows-latest
            vtk-system: true

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.os == 'ubuntu-latest' && 'fedora:38' || null }}

    name: '🧪 Test on ${{ matrix.os }} [Config: "${{ matrix.config }}", VTK installed: "${{ matrix.vtk-system }}"]'

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 📋 Install Dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: dnf install -y make automake gcc gcc-c++ kernel-devel cmake git

      - name: 📋 Install VTK
        if: ${{ matrix.vtk-system }}
        run: dnf install -y vtk vtk-devel

      - name: 📋 Setup OpenMP
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew reinstall --build-from-source --formula ./.github/homebrew/libomp.rb

      - name: 🩹 Enable Long Paths
        # Workaround for windows, as the filename is 260 by default, however
        # VTK has some files that exceed this limit, thus we need this workaround.
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - name: 🦥 Cache Dependencies
        uses: actions/cache@v3
        with:
          key: ${{ matrix.os }}-${{ matrix.config }}-cache
          path: |
            deps-cache
            build

      - name: 🏗️ Compile
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCPM_SOURCE_CACHE=deps-cache -DVIENNALS_BUILD_TESTS=ON -B build && cmake --build build

      - name: 🧪 Test
        run: ctest -E "Benchmark|Performance" --test-dir build
